Repository rustic-rs/rustic_core, pull requests merged in 2024-03, with the labels that each got.

#176 feat!: move clippy lints to cargo manifest and fix upcoming issues all over the workspace
  Cargo.toml
  README.md
  crates/backend/Cargo.toml
  crates/backend/src/choose.rs
  crates/backend/src/error.rs
  crates/backend/src/lib.rs
  crates/backend/src/local.rs
  crates/backend/src/opendal.rs
  crates/backend/src/opendal/s3.rs
  crates/backend/src/opendal/sftp.rs
  crates/backend/src/rclone.rs
  crates/backend/src/rest.rs
  crates/backend/src/util.rs
  crates/config/Cargo.toml
  crates/config/src/lib.rs
  crates/core/Cargo.toml
  crates/core/src/archiver.rs
  crates/core/src/backend.rs
  crates/core/src/backend/cache.rs
  crates/core/src/backend/ignore.rs
  crates/core/src/backend/local_destination.rs
  crates/core/src/backend/node.rs
  crates/core/src/blob/packer.rs
  crates/core/src/cdc/polynom.rs
  crates/core/src/commands/backup.rs
  crates/core/src/commands/merge.rs
  crates/core/src/commands/prune.rs
  crates/core/src/commands/repair/index.rs
  crates/core/src/commands/restore.rs
  crates/core/src/error.rs
  crates/core/src/id.rs
  crates/core/src/lib.rs
  crates/core/src/repofile/configfile.rs
  crates/core/src/repofile/snapshotfile.rs
  crates/core/src/repository.rs
  crates/core/src/vfs.rs
  crates/testing/Cargo.toml
  crates/testing/src/lib.rs
  examples/backup/examples/backup.rs
  examples/check/examples/check.rs
  examples/config/examples/config.rs
  examples/copy/examples/copy.rs
  examples/forget/examples/forget.rs
  examples/init/examples/init.rs
  examples/key/examples/key.rs
  examples/ls/examples/ls.rs
  examples/merge/examples/merge.rs
  examples/prune/examples/prune.rs
  examples/restore/examples/restore.rs
  examples/tag/examples/tag.rs
Labels: A-meta, C-refactor

#175 test: add backup integration tests using snapshots
  .github/workflows/ci-heavy.yml
  .github/workflows/ci.yml
  .gitignore
  Cargo.toml
  crates/core/Cargo.toml
  crates/core/src/backend.rs
  crates/core/src/commands/merge.rs
  crates/core/src/lib.rs
  crates/core/src/repofile/snapshotfile.rs
  crates/core/src/repository.rs
  crates/core/tests/fixtures/backup-data.tar.gz
  crates/core/tests/integration.rs
  crates/core/tests/snapshots/integration__backup-tar-summary-first-nix.snap
  crates/core/tests/snapshots/integration__backup-tar-summary-first-windows.snap
  crates/core/tests/snapshots/integration__backup-tar-summary-second-nix.snap
  crates/core/tests/snapshots/integration__backup-tar-summary-second-windows.snap
  crates/core/tests/snapshots/integration__backup-tar-tree-nix.snap
  crates/core/tests/snapshots/integration__backup-tar-tree-windows.snap
  crates/core/tests/snapshots/integration__dryrun-tar-summary-first-nix.snap
  crates/core/tests/snapshots/integration__dryrun-tar-summary-first-windows.snap
  crates/core/tests/snapshots/integration__dryrun-tar-summary-second-nix.snap
  crates/core/tests/snapshots/integration__dryrun-tar-summary-second-windows.snap
  crates/core/tests/snapshots/integration__dryrun-tar-tree-nix.snap
  crates/core/tests/snapshots/integration__dryrun-tar-tree-windows.snap
  crates/testing/Cargo.toml
  crates/testing/src/backend.rs
  crates/testing/src/lib.rs
Labels: A-testing, C-enhancement

#200 feat(backend)!: remove s3 and sftp wrapper around opendal
  crates/backend/Cargo.toml
  crates/backend/README.md
  crates/backend/src/choose.rs
  crates/backend/src/lib.rs
  crates/backend/src/opendal.rs
  crates/backend/src/opendal/s3.rs
  crates/backend/src/opendal/sftp.rs
  crates/backend/src/util.rs
Labels: A-backends, C-refactor
