Repository rustic-rs/rustic_core, pull requests merged in 2024-10, with the labels that each got.

#291 fix(backend)!: Use correct merge stratgy for repository options
  crates/backend/src/choose.rs
Labels: M-breaking, S-blocked, A-backends, C-refactor, M-breaking-docs-todo

#295 ci: don't run heavy ci on push to main
  .github/workflows/ci-heavy.yml
Labels: A-ci, C-enhancement

#299 fix: fix check without --read-data
  crates/core/src/commands/check.rs
Labels: C-bug

#302 ci: add triage label to new issues only if no label has been set when creating it
  .github/workflows/triage.yml
Labels: A-ci, C-bug

#303 ci: generate lockfile in ci for rustsec/audit-check
  .github/workflows/audit.yml
Labels: A-ci, C-bug

#297 fix(errors): better error message for hot/cold repo in check
  crates/core/src/commands/check.rs
Labels: A-errors, C-bug

#323 fix(errors): use correct error variant for data encryption
  crates/core/src/crypto/aespoly1305.rs
  crates/core/src/error.rs
Labels: A-errors, C-bug, S-waiting-for-review

#314 refactor(errors): improve message and add logging when sending tree from backend panics
  crates/core/src/blob/tree.rs
Labels: C-bug, S-waiting-for-review, I-panic

#317 refactor(commands): decouple logic from option structs for check, prune, repair, key, and restore
  crates/core/src/commands/check.rs
  crates/core/src/commands/init.rs
  crates/core/src/commands/key.rs
  crates/core/src/commands/prune.rs
  crates/core/src/commands/repair/index.rs
  crates/core/src/commands/repair/snapshots.rs
  crates/core/src/commands/restore.rs
  crates/core/src/repository.rs
  crates/core/tests/command_input.rs
  crates/core/tests/integration.rs
Labels: A-testing, S-waiting-for-review, A-api, A-dx, C-refactor

#335 chore(deps): commit lockfile due to broken CI pipelines
  .gitignore
  Cargo.lock
Labels: A-dependencies, C-refactor

#331 fix: OpenFile::read_at no longer errors on invalid offset or length
  crates/core/src/repository.rs
  crates/core/src/vfs.rs
  crates/core/tests/integration.rs
Labels: C-bug

#328 feat(commands): Add convenient names for read-data-subset n/m
  crates/core/src/commands/check.rs
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_15_month_hours.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_29_28.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_4_month_days.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_5_12.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_daily_15.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_daily_month.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_daily_week.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_daily_year.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_hourly_20.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_hourly_day.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_hourly_month.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_hourly_week.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_hourly_year.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_monthly_5.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_monthly_year.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_weekly_10.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_weekly_month.snap
  crates/core/src/commands/snapshots/rustic_core__commands__check__tests__n_m_weekly_year.snap
Labels: C-enhancement, A-commands

#340 fix: opendal paths on windows
  Cargo.lock
  crates/backend/Cargo.toml
  crates/backend/src/opendal.rs
Labels: C-bug, O-windows, A-backends

#342 fix(errors): forwarding Display impl should work again
  crates/core/src/error.rs
Labels: A-errors, C-bug, A-dx
