Repository rustic-rs/rustic_core, pull requests merged in 2024-09, with the labels that each got.

#269 feat!: Use CommandInput for commands
  crates/backend/Cargo.toml
  crates/backend/src/error.rs
  crates/backend/src/local.rs
  crates/backend/src/rclone.rs
  crates/core/src/repository.rs
  crates/core/src/repository/warm_up.rs
  crates/core/tests/integration.rs
Labels: M-breaking, M-breaking-docs-done

#266 feat(commands): Add option stdin_command to be used in CLI and config file
  crates/core/src/backend.rs
  crates/core/src/backend/childstdout.rs
  crates/core/src/backend/stdin.rs
  crates/core/src/commands/backup.rs
  crates/core/src/error.rs
  crates/core/src/repository/command_input.rs
  crates/core/tests/integration.rs
  crates/core/tests/snapshots/integration__stdin-command-summary-nix.snap
  crates/core/tests/snapshots/integration__stdin-command-summary-windows.snap
Labels: A-commands, A-config

#267 fix!: use plural names for options
  crates/core/src/backend/ignore.rs
  crates/core/src/commands/forget.rs
  crates/core/src/commands/snapshots/rustic_core__commands__forget__tests__keep-ids[23ef].snap
  crates/core/src/commands/snapshots/rustic_core__commands__forget__tests__keep-tags[bar,foo].snap
  crates/core/src/commands/snapshots/rustic_core__commands__forget__tests__keep-tags[foo].snap
  crates/core/src/repofile/snapshotfile.rs
  crates/core/tests/integration.rs
Labels: M-breaking, M-breaking-docs-done

#256 refactor!: Use different Id types
  crates/backend/src/local.rs
  crates/backend/src/opendal.rs
  crates/backend/src/rest.rs
  crates/core/Cargo.toml
  crates/core/src/archiver.rs
  crates/core/src/archiver/file_archiver.rs
  crates/core/src/archiver/parent.rs
  crates/core/src/archiver/tree_archiver.rs
  crates/core/src/backend.rs
  crates/core/src/backend/cache.rs
  crates/core/src/backend/decrypt.rs
  crates/core/src/backend/node.rs
  crates/core/src/blob.rs
  crates/core/src/blob/packer.rs
  crates/core/src/blob/tree.rs
  crates/core/src/commands/backup.rs
  crates/core/src/commands/cat.rs
  crates/core/src/commands/check.rs
  crates/core/src/commands/copy.rs
  crates/core/src/commands/dump.rs
  crates/core/src/commands/forget.rs
  crates/core/src/commands/init.rs
  crates/core/src/commands/key.rs
  crates/core/src/commands/merge.rs
  crates/core/src/commands/prune.rs
  crates/core/src/commands/repair/index.rs
  crates/core/src/commands/repair/snapshots.rs
  crates/core/src/commands/restore.rs
  crates/core/src/error.rs
  crates/core/src/id.rs
  crates/core/src/index.rs
  crates/core/src/index/binarysorted.rs
  crates/core/src/index/indexer.rs
  crates/core/src/lib.rs
  crates/core/src/repofile.rs
  crates/core/src/repofile/configfile.rs
  crates/core/src/repofile/indexfile.rs
  crates/core/src/repofile/keyfile.rs
  crates/core/src/repofile/packfile.rs
  crates/core/src/repofile/snapshotfile.rs
  crates/core/src/repository.rs
  crates/core/src/repository/warm_up.rs
  crates/core/src/vfs.rs
  crates/core/tests/integration.rs
Labels: M-breaking

#166 feat: Add Repository::drop_index and ::drop_data_from_index
  crates/core/src/index.rs
  crates/core/src/index/binarysorted.rs
  crates/core/src/lib.rs
  crates/core/src/repository.rs
  crates/core/tests/integration.rs
Labels: C-enhancement, perf

#271 doc: remove readme versions in usage section for easier release due to release PR
  crates/backend/README.md
  crates/config/README.md
  crates/core/README.md
Labels: A-docs
