Repository rustic-rs/rustic_core, pull requests merged in 2024-11, with the labels that each got.

#349 ci: use runners according to available images and target triple
  .github/workflows/ci-heavy.yml
  .github/workflows/cross-ci.yml
Labels: A-ci, C-enhancement

#300 refactor(deps)!: upgrade to new conflate version
  Cargo.lock
  crates/backend/Cargo.toml
  crates/backend/src/choose.rs
  crates/backend/src/opendal.rs
  crates/backend/src/rclone.rs
  crates/core/Cargo.toml
Labels: A-dependencies, M-breaking, C-refactor

#348 refactor(deps): remove cdc and switch to rustic_cdc
  Cargo.lock
  crates/core/Cargo.toml
  crates/core/src/archiver/file_archiver.rs
  crates/core/src/cdc.rs
  crates/core/src/cdc/LICENSE.txt
  crates/core/src/cdc/README.md
  crates/core/src/cdc/polynom.rs
  crates/core/src/cdc/rolling_hash.rs
  crates/core/src/chunker.rs
  crates/core/src/lib.rs
Labels: A-dependencies, C-refactor

#334 refactor(error): improve error messages and file handling
  crates/backend/src/local.rs
  crates/core/src/commands/check.rs
Labels: A-errors, S-waiting-for-review, C-refactor

#362 refactor(backend): simplify code in local backend
  crates/backend/src/local.rs
Labels: A-backends, C-refactor

#361 refactor(error): enhance error logging and output formatting
  crates/backend/src/local.rs
  crates/backend/src/opendal.rs
  crates/core/src/archiver.rs
  crates/core/src/archiver/parent.rs
  crates/core/src/backend/cache.rs
  crates/core/src/backend/ignore.rs
  crates/core/src/commands/backup.rs
  crates/core/src/commands/check.rs
  crates/core/src/commands/repair/index.rs
  crates/core/src/commands/repair/snapshots.rs
  crates/core/src/error.rs
  crates/core/src/repofile/snapshotfile.rs
  crates/core/src/repository/warm_up.rs
  crates/core/tests/errors.rs
  crates/core/tests/snapshots/errors__log_output_minimal_passes.snap
  crates/core/tests/snapshots/errors__log_output_passes.snap
Labels: A-errors, C-enhancement, A-dx, C-refactor

#355 feat(async): add `async_compatible` methods to identify backend compatibility
  crates/backend/src/local.rs
  crates/backend/src/opendal.rs
  crates/backend/src/rclone.rs
  crates/backend/src/rest.rs
  crates/core/src/backend.rs
  crates/core/src/backend/cache.rs
  crates/core/src/backend/decrypt.rs
  crates/core/src/backend/dry_run.rs
  crates/core/src/backend/hotcold.rs
  crates/core/src/backend/warm_up.rs
  crates/core/src/repository.rs
  crates/testing/src/backend.rs
Labels: A-backends, A-api
